import time
name = input("Enter your name:")
n = len(name)
def cake():
    print("\n","*12","iii")
    y = time.sleep(1)
    print(""*11,"iiii")
    y = time.sleep(1)
    print(""*9,"i_i_i_i_i_i_i")
    y = time.sleep(1)
    print(""*9,"|","*9,""|")
    y = time.sleep(1)
    print(""*9,"|","*9,""|")
    y = time.sleep(1)
    print(""*6,"-"*19)
    y = time.sleep(1)
    print(""*6,"|",""*int((13-n)/2),name,""*int((18-n)/2-2),"|")
    y = time.sleep(1)
    print(""*6,"|",""*15,"|")
    y = time.sleep(1)
    print(""*3,"-"*25)
    y = time.sleep(1)
    print(""*2,"Many many RETURNS of the day")
    print("Happy birthday to you")
    y = time.sleep(1)
    print("Happy birthday to you")
    y = time.sleep(1)
    print("Happy birthday to you")
    y = time.sleep(1)
    print("Happy birthdayt to",name)
    y = time.sleep(1)
    print("happy birthday to you")
    y = time.sleep(1)
    cake()
